import 'package:flutter/material.dart';
import 'package:sokonumber_flutter/models/cell.dart';

final Map<int, dynamic> levels = {
  1: [
    Cell(index: 0, type: 3, isSwipeable: false),
    Cell(index: 1, type: 3, isSwipeable: false),
    Cell(index: 2, type: 3, isSwipeable: false),
    Cell(
        index: 3,
        type: 1,
        isSwipeable: true,
        n: 1,
        offsets: [Offset(1.0, 0.0)]),
    Cell(index: 4, type: 2, isSwipeable: false),
    Cell(index: 5, type: 4, isSwipeable: false, n: 1),
    Cell(index: 6, type: 3, isSwipeable: false),
    Cell(index: 7, type: 3, isSwipeable: false),
    Cell(index: 8, type: 3, isSwipeable: false),
  ],
  11: 1,
  111: 1,
  2: [
    Cell(index: 0, type: 3, isSwipeable: false),
    Cell(
        index: 1,
        type: 1,
        isSwipeable: true,
        n: 1,
        offsets: [Offset(0.0, 1.0)]),
    Cell(index: 2, type: 3, isSwipeable: false),
    Cell(
        index: 3,
        type: 1,
        isSwipeable: true,
        n: 2,
        offsets: [Offset(0.0, 1.0)]),
    Cell(index: 4, type: 3, isSwipeable: false),
    Cell(index: 5, type: 3, isSwipeable: false),
    Cell(index: 6, type: 2, isSwipeable: false),
    Cell(index: 7, type: 3, isSwipeable: false),
    Cell(index: 8, type: 2, isSwipeable: false),
    Cell(index: 9, type: 3, isSwipeable: false),
    Cell(index: 10, type: 3, isSwipeable: false),
    Cell(index: 11, type: 2, isSwipeable: false),
    Cell(index: 12, type: 3, isSwipeable: false),
    Cell(index: 13, type: 2, isSwipeable: false),
    Cell(index: 14, type: 3, isSwipeable: false),
    Cell(index: 15, type: 3, isSwipeable: false),
    Cell(index: 16, type: 2, isSwipeable: false),
    Cell(index: 17, type: 3, isSwipeable: false),
    Cell(index: 18, type: 2, isSwipeable: false),
    Cell(index: 19, type: 3, isSwipeable: false),
    Cell(index: 20, type: 3, isSwipeable: false),
    Cell(index: 21, type: 4, isSwipeable: false, n: 1),
    Cell(index: 22, type: 3, isSwipeable: false),
    Cell(index: 23, type: 4, isSwipeable: false, n: 2),
    Cell(index: 24, type: 3, isSwipeable: false),
  ],
  22: 2,
  222: 5,
  3: [
    Cell(index: 0, type: 1, isSwipeable: true, offsets: [Offset(1.0, 0)], n: 1),
    Cell(index: 1, type: 4, isSwipeable: false, n: 2),
    Cell(index: 2, type: 2, isSwipeable: false),
    Cell(index: 3, type: 3, isSwipeable: false),
    Cell(index: 4, type: 2, isSwipeable: false),
    Cell(index: 5, type: 3, isSwipeable: false),
    Cell(index: 6, type: 2, isSwipeable: false),
    Cell(index: 7, type: 4, isSwipeable: false, n: 1),
    Cell(index: 8, type: 1, isSwipeable: true, offsets: [Offset(-1, 0)], n: 2)
  ],
  33: 2,
  333: 7,
  4: [
    Cell(index: 0, type: 3, isSwipeable: false),
    Cell(index: 1, type: 3, isSwipeable: false),
    Cell(index: 2, type: 3, isSwipeable: false),
    Cell(index: 3, type: 3, isSwipeable: false),
    Cell(index: 4, type: 3, isSwipeable: false),
    Cell(index: 5, type: 1, isSwipeable: true, offsets: [Offset(0, 1)], n: 1),
    Cell(index: 6, type: 3, isSwipeable: false),
    Cell(index: 7, type: 1, isSwipeable: true, offsets: [Offset(0, 1)], n: 2),
    Cell(index: 8, type: 3, isSwipeable: false),
    Cell(index: 9, type: 1, isSwipeable: true, offsets: [Offset(0, 1)], n: 3),
    Cell(index: 10, type: 4, isSwipeable: false, n: 3),
    Cell(index: 11, type: 2, isSwipeable: false),
    Cell(index: 12, type: 4, isSwipeable: false, n: 2),
    Cell(index: 13, type: 2, isSwipeable: false),
    Cell(index: 14, type: 4, isSwipeable: false, n: 1),
    Cell(index: 15, type: 3, isSwipeable: false),
    Cell(index: 16, type: 3, isSwipeable: false),
    Cell(index: 17, type: 2, isSwipeable: false),
    Cell(index: 18, type: 3, isSwipeable: false),
    Cell(index: 19, type: 3, isSwipeable: false),
    Cell(index: 20, type: 2, isSwipeable: false),
    Cell(index: 21, type: 3, isSwipeable: false),
    Cell(index: 22, type: 3, isSwipeable: false),
    Cell(index: 23, type: 3, isSwipeable: false),
    Cell(index: 24, type: 2, isSwipeable: false),
  ],
  44: 3,
  444: 9,
  5: [
    Cell(
      index: 0,
      type: 1,
      isSwipeable: true,
      n: 1,
      offsets: [Offset(0.0, 1.0)],
    ),
    Cell(index: 1, type: 3, isSwipeable: false),
    Cell(index: 2, type: 3, isSwipeable: false),
    Cell(index: 3, type: 3, isSwipeable: false),
    Cell(index: 4, type: 4, isSwipeable: false, n: 1),
    Cell(
      index: 5,
      type: 1,
      isSwipeable: true,
      n: 2,
      offsets: [
        Offset(0.0, 1.0),
        Offset(-1.0, 0.0),
      ],
    ),
    Cell(
      index: 6,
      type: 3,
      isSwipeable: false,
    ),
    Cell(
      index: 7,
      type: 2,
      isSwipeable: false,
    ),
    Cell(
      index: 8,
      type: 2,
      isSwipeable: false,
    ),
    Cell(index: 9, type: 4, isSwipeable: false, n: 2),
    Cell(
      index: 10,
      type: 1,
      isSwipeable: true,
      n: 3,
      offsets: [
        Offset(0.0, 1.0),
        Offset(1.0, 0.0),
        Offset(-1.0, 0.0),
      ],
    ),
    Cell(index: 11, type: 4, isSwipeable: false, n: 4),
    Cell(
      index: 12,
      type: 2,
      isSwipeable: false,
    ),
    Cell(
      index: 13,
      type: 2,
      isSwipeable: false,
    ),
    Cell(index: 14, type: 4, isSwipeable: false, n: 3),
    Cell(
      index: 15,
      type: 1,
      isSwipeable: true,
      n: 4,
      offsets: [
        Offset(0.0, -1.0),
        Offset(-1.0, 0.0),
      ],
    ),
  ],
  55: 4,
  555: 12,
  6: [
    Cell(
      type: 2,
      isSwipeable: false,
      index: 0,
    ),
    Cell(index: 1, type: 2, isSwipeable: false),
    Cell(
        index: 2,
        type: 1,
        isSwipeable: true,
        n: 2,
        offsets: [
          Offset(0.0, 1.0),
          Offset(-1.0, 0.0),
        ],
        isMatch: true,
        instead: Cell(
          index: 2,
          type: 4,
          isSwipeable: false,
          n: 2,
        )),
    Cell(index: 3, type: 3, isSwipeable: false),
    Cell(index: 4, type: 2, isSwipeable: false),
    Cell(
      index: 5,
      type: 1,
      isSwipeable: true,
      n: 1,
      offsets: [
        Offset(0.0, -1.0),
        Offset(1.0, 0.0),
        Offset(-1.0, 0.0),
      ],
    ),
    Cell(
      index: 6,
      type: 4,
      isSwipeable: false,
      n: 1,
    ),
    Cell(
        index: 7,
        type: 1,
        isSwipeable: true,
        n: 5,
        offsets: [
          Offset(0.0, 1.0),
          Offset(-1.0, 0.0),
        ],
        isMatch: true,
        instead: Cell(
          index: 7,
          type: 4,
          isSwipeable: false,
          n: 5,
        )),
    Cell(
      index: 8,
      type: 1,
      isSwipeable: true,
      n: 3,
      offsets: [Offset(0.0, -1.0)],
    ),
    Cell(index: 9, type: 3, isSwipeable: false),
    Cell(
        index: 10,
        type: 1,
        isSwipeable: true,
        n: 4,
        offsets: [
          Offset(0.0, -1.0),
          Offset(1.0, 0.0),
        ],
        instead: Cell(
          index: 10,
          type: 4,
          isSwipeable: false,
          n: 3,
        )),
    Cell(
      index: 11,
      type: 4,
      isSwipeable: false,
      n: 4,
    ),
    Cell(index: 12, type: 3, isSwipeable: false),
    Cell(index: 13, type: 3, isSwipeable: false),
    Cell(index: 14, type: 3, isSwipeable: false),
    Cell(index: 15, type: 3, isSwipeable: false),
  ],
};
